### ISSUE TITLE
App Pizzeria

### ISSUE THREAD

**Issue by eridal** [111utn/app-pizzeria#21]
# Casos de Uso:

## Cajero
- [ ] Generar cliente: #11 
- [ ] Generar Pedido: #13
- [ ] Generar Factura #14 
- [ ] Consultar Menu: #15 
- [ ] Consultar Estado Pedido: #16 

## Cocina
- [ ] Consultar Nuevo Pedido: #17 
- [ ] Informar Pedido Listo: #18
